/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author alunos
 */
public class Tela1_GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Tela1_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        val_box = new javax.swing.JTextField();
        Val_BTN = new javax.swing.JButton();
        Val_text = new javax.swing.JLabel();
        Sair1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Gerar_BTN = new javax.swing.JButton();
        Gerar_text = new javax.swing.JLabel();
        Sair2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel1.setLayout(null);

        val_box.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(val_box);
        val_box.setBounds(90, 70, 160, 40);

        Val_BTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Val_BTN.setText("validar");
        Val_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Val_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Val_BTN);
        Val_BTN.setBounds(300, 170, 110, 50);

        Val_text.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jPanel1.add(Val_text);
        Val_text.setBounds(40, 100, 220, 90);

        Sair1.setText("X");
        Sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair1ActionPerformed(evt);
            }
        });
        jPanel1.add(Sair1);
        Sair1.setBounds(350, 20, 50, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel3.setText("CPF:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 60, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setText("Validador");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 170, 30);

        jTabbedPane1.addTab("validador", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setText("CPF:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 90, 40);

        Gerar_BTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Gerar_BTN.setText("gerar");
        Gerar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gerar_BTNActionPerformed(evt);
            }
        });
        jPanel2.add(Gerar_BTN);
        Gerar_BTN.setBounds(150, 160, 110, 50);

        Gerar_text.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jPanel2.add(Gerar_text);
        Gerar_text.setBounds(100, 60, 270, 60);

        Sair2.setText("X");
        Sair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair2ActionPerformed(evt);
            }
        });
        jPanel2.add(Sair2);
        Sair2.setBounds(340, 20, 50, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Gerador");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 170, 30);

        jTabbedPane1.addTab("gerador", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(441, 270));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Sair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair2ActionPerformed
        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_Sair2ActionPerformed

    private void Gerar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gerar_BTNActionPerformed
        model.Gerar_CPF.funci();
    }//GEN-LAST:event_Gerar_BTNActionPerformed

    private void Sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Sair1ActionPerformed

    private void Val_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Val_BTNActionPerformed
        model.Val_CPF.funci();        // TODO add your handling code here:
    }//GEN-LAST:event_Val_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gerar_BTN;
    public static javax.swing.JLabel Gerar_text;
    private javax.swing.JButton Sair1;
    private javax.swing.JButton Sair2;
    private javax.swing.JButton Val_BTN;
    public static javax.swing.JLabel Val_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField val_box;
    // End of variables declaration//GEN-END:variables
}
