/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author alunos
 */
public class tela1_GUI extends javax.swing.JFrame {

    /**
     * Creates new form tela1_GUI
     */
    public tela1_GUI() {
        initComponents();
        magro_IMG.setVisible(false);
        normal_IMG.setVisible(false);
        acimaDoPeso.setVisible(false);
        Obeso1_img.setVisible(false);
        Obeso2_IMG.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel1 = new javax.swing.JPanel();
        Peso_DOA = new javax.swing.JTextField();
        Altura_DOA = new javax.swing.JTextField();
        IMC_TXT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Calcular_BNT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Obeso2_IMG = new javax.swing.JLabel();
        magro_IMG = new javax.swing.JLabel();
        normal_IMG = new javax.swing.JLabel();
        Obeso1_img = new javax.swing.JLabel();
        acimaDoPeso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Painel1.setBackground(new java.awt.Color(102, 153, 255));
        Painel1.setLayout(null);

        Peso_DOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Peso_DOAActionPerformed(evt);
            }
        });
        Painel1.add(Peso_DOA);
        Peso_DOA.setBounds(36, 67, 118, 20);

        Altura_DOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Altura_DOAActionPerformed(evt);
            }
        });
        Painel1.add(Altura_DOA);
        Altura_DOA.setBounds(232, 67, 118, 20);

        IMC_TXT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Painel1.add(IMC_TXT);
        IMC_TXT.setBounds(36, 116, 157, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Altura:");
        Painel1.add(jLabel2);
        jLabel2.setBounds(232, 36, 71, 18);

        Calcular_BNT.setBackground(new java.awt.Color(0, 153, 204));
        Calcular_BNT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Calcular_BNT.setText("Calcular");
        Calcular_BNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular_BNTActionPerformed(evt);
            }
        });
        Painel1.add(Calcular_BNT);
        Calcular_BNT.setBounds(419, 35, 130, 52);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Peso:");
        Painel1.add(jLabel3);
        jLabel3.setBounds(44, 35, 75, 21);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Painel1.add(jButton1);
        jButton1.setBounds(540, 420, 60, 23);

        Obeso2_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Obeso2.png"))); // NOI18N
        Painel1.add(Obeso2_IMG);
        Obeso2_IMG.setBounds(500, 200, 100, 179);

        magro_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magro.png"))); // NOI18N
        Painel1.add(magro_IMG);
        magro_IMG.setBounds(20, 200, 100, 179);

        normal_IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/normal.png"))); // NOI18N
        Painel1.add(normal_IMG);
        normal_IMG.setBounds(140, 200, 100, 178);

        Obeso1_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Obeso1.png"))); // NOI18N
        Painel1.add(Obeso1_img);
        Obeso1_img.setBounds(390, 200, 100, 176);

        acimaDoPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acimaDoPeso.png"))); // NOI18N
        Painel1.add(acimaDoPeso);
        acimaDoPeso.setBounds(260, 200, 100, 177);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(609, 449));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Altura_DOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Altura_DOAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Altura_DOAActionPerformed

    private void Calcular_BNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular_BNTActionPerformed
        magro_IMG.setVisible(false);
        normal_IMG.setVisible(false);
        acimaDoPeso.setVisible(false);
        Obeso1_img.setVisible(false);
        Obeso2_IMG.setVisible(false);
        model.Funcionalidades_DOA.funci();
        
    }//GEN-LAST:event_Calcular_BNTActionPerformed

    private void Peso_DOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Peso_DOAActionPerformed
     
    }//GEN-LAST:event_Peso_DOAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela1_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Altura_DOA;
    private javax.swing.JButton Calcular_BNT;
    public static javax.swing.JLabel IMC_TXT;
    public static javax.swing.JLabel Obeso1_img;
    public static javax.swing.JLabel Obeso2_IMG;
    public static javax.swing.JPanel Painel1;
    public static javax.swing.JTextField Peso_DOA;
    public static javax.swing.JLabel acimaDoPeso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel magro_IMG;
    public static javax.swing.JLabel normal_IMG;
    // End of variables declaration//GEN-END:variables
}
